# Generated by Django 5.1.4 on 2025-01-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Inprogress', 'Inprogress'), ('Resolved', 'Resolved'), ('Reopened', 'Reopened'), ('closed', 'closed')], default='New', max_length=50),
        ),
    ]
